### ISSUE TITLE
Github Actions workflow does not seem to be triggering on currently open PRs

### ISSUE THREAD

**Issue by harrisonCassar** [Bruin-Spacecraft-Group/SPARTAN#50]
After merging #41, I expected to see any new PRs or pushes to branches associated with open PRs to be ran automatically with the new Github Actions workflow, but it doesn't seem to be triggering.

Perhaps we have the configuration on our trigger events wrong? Here's some quick resources that may be handy:
- https://github.community/t/trigger-workflow-for-a-pull-request-and-for-all-subsequent-commits-in-it/17996
- https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow

cc: @kevinl120

**Comment by kevinl120** [comment]
@harrisonCassar I configured the build task to run on pull requests only, that seems to be working as intended (e.g. [here](https://github.com/Bruin-Spacecraft-Group/SPARTAN/pull/40)). For existing pull requests, the task won't run unless there have been new commits. If it's preferred, I can edit the configuration to build on every commit.

**Comment by harrisonCassar** [comment]
Ah, woops, you're right! We'll leave it as is then.
